# Matrix Multiplication

In [2]:
import numpy as np
import Matrix_Mult_Func as mmf

In [3]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

In [4]:
# calling the matrix multiplcation function from the VIM file

mmf.mat_mult(a, b)

array([[19., 22.],
       [43., 50.]])

In [5]:
# calling the matrix multiplcation function from the VIM file

mmf.mat_mult2(a, b)

array([[19., 22.],
       [43., 50.]])

In [12]:
print("First row of Matrix A:", a[0])
print("First column of matrix B:", b[:,0])
print("Shape of Matrix A:", np.shape(a))

First row of Matrix A: [1 2]
First column of matrix B: [5 7]
Shape of Matrix A: (2, 2)


### Generalize the function for any size and shape matrix using NumPy:

In [109]:
a = np.array([[1, 2], [3, 4]])
b = np.array([1, 2])
c = np.array([[1, 2, 5], [3, 4, 5]])
d = np.array([[1, 2], [2, 3], [3, 4]])
len(a), len(b), len(c)

(2, 2, 2)

In [112]:
np.shape(a), np.shape(b), np.shape(c), np.shape(d)

((2, 2), (2,), (2, 3), (3, 2))

In [104]:
def rows_and_cols(x):
    y = np.shape(x)
    z = len(y)
    if z > 1:
        return y
    else:
        return (y[0], 1)

In [105]:
rows_and_cols(np.array([1, 2, 3, 4, 5]))

(5, 1)

In [129]:
def mat_sq_col1(aa, bb):
    dim_aa = rows_and_cols(aa)
    dim_bb = rows_and_cols(bb)
    assert dim_aa[1] == dim_bb[0], print("Matrices cannot be multiplied")
    
    cc = np.zeros((dim_aa[0], dim_bb[1]))
    if dim_bb[1] == 1:
        cc = cc.flatten()
        for ii in range(0, dim_aa[0]):
            cc[ii] = np.sum(aa[ii]*bb)
    else:
        for ii in range(0, dim_aa[0]):
            for jj in range(0, dim_bb[1]):
                cc[ii, jj] = np.sum(aa[ii]*bb[:,jj])
    return cc

In [135]:
mat_sq_col1(f, g)

array([[15., 30., 45., 60.],
       [15., 30., 45., 60.],
       [15., 30., 45., 60.],
       [15., 30., 45., 60.]])

In [134]:
f = np.array([[1, 2, 3, 4, 5],
              [1, 2, 3, 4, 5],
              [1, 2, 3, 4, 5],
              [1, 2, 3, 4, 5]])

g = np.array([[1, 2, 3, 4],
              [1, 2, 3, 4],
              [1, 2, 3, 4],
              [1, 2, 3, 4],
              [1, 2, 3, 4]])

xx = mat_sq_col1(ff, gg)
print(xx, np.shape(xx))

[[15. 30. 45. 60.]
 [15. 30. 45. 60.]
 [15. 30. 45. 60.]
 [15. 30. 45. 60.]] (4, 4)
