In [1]:
import numpy as np
import 

In [12]:
A = np.array([1, 2, 3, 4])
B = np.array([5, 6, 7, 8])

In [13]:
mat_mult(A, B)

array([[19, 22],
       [43, 50]])

### Generalize the function for any size matrices of the same shape:

In [39]:
a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])
mat_mult2(a, b)
np.dot(a, b)

array([[19, 22],
       [43, 50]])

In [40]:
a[0]   # row
b[:,0] # column

array([5, 7])

### Generalize the function for any size matrices of the same shape using NumPy:

In [85]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[1, 0, 0], [0, 1, 0], [0, 0, 1]])
mat_mult3(a, b)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [66]:
array1 = np.array([[1, 2],
          [3, 4]])

array2 = np.array([[5, 7],
                   [6, 8]])

array3 = (array1 * array2.T).sum(axis=1)
print(array3)

[17 53]


In [70]:
a = np.array([[1, 2], [3, 4]])

In [78]:
a

array([[1, 2],
       [3, 4]])

In [82]:
len(a)

2